# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  use_frameworks!
target 'Chief' do
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

end
